baseURL = 'https://wilkuu.xyz'
languageCode = 'en-us'
title = "Wilkuu's little site"
theme = "terminal"
enableRobotsTXT = true

copyright = "Wilkuu"
pagination.pagerSize = 8
summaryLenghh = 1

[markup.highlight]
  noClasses = false 

[sitemap]
  changefreq = 'weekly'
  disable = false
  priority = 1

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "projects"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true 

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"

    # Ficurina things 
    # author = "Wilkuu - [source](https://github.com/Wilkuu-2/wilkuu.xyz) "
    # description = "A blog about some mediocre stuff"  # this will be added as metadata
    #
    # posts = "posts"  # content directory where to find home page posts; default searches in "posts" and "post"
    # showPostsLink = true  # show or hide the link to the simple post list
    # extraContentDirs = [ "projects" ]  # other content directories to render similarly to the home page
    # showcaseDir = "showcase"  # create a content directory that shows a special showcase section in the home page
    #
    # # shows a specified single page as a home page, instead of the traditional articles list
    # # requires setting `homeSinglePage`
    # # goes well with extraContentDirs
    # showSinglePageAsHome = false
    # homeSinglePage = "/home"
    #
    # # It's best to put these icons in the "static" folder of your site
    # logo = "/logo.svg"
    # favicon = "/favicon.png"  # 32x32
    # faviconIco = "/favicon.ico"  # 32x32
    # appletouch = "/apple-touch-icon.png"  # 180x180
    # svgicon = "/logo.svg"
    # icon512 = "/icon512.png"  # 512x512 png image
    #
    # logoRightOfTitle = false  # positions the logo to the right of the title; default: false
    #
    # showTags = true  # show the Tags menu item; default true
    # showRss = true  # show the link for the RSS feed; default true
    #
    # imageInArticlePreview = false  # show images in article preview; default false
    # fitImageInArticlePreview = false  # make article preview images fit the article preview instead of getting cropped
    # articleSummary = true  # show a summary in article preview; default true
    # 
    # fontFamily = "JetBrains Mono"  # changes the font, default "JetBrains Mono"
    # titleFontFamily = "JetBrains Mono"  # font used for titles and headings
    # monospaceFontFamily = "JetBrains Mono"  # changes the monospace font for code, default "JetBrains Mono"
    #
    # # multipliers applied to font sizes, useful for custom fonts that may be too big or too small
    # titleFontSizeMultiplier = 1.0
    # mainFontSizeMultiplier = 1.0
    # monoFontSizeMultiplier = 1.0
    #
    # contentWidth = "1000px"  # maximum width of the site content, css syntax
    #
    # paperCards = false  # enable paper card style; default false
    # buttonTags = false  # enable button tag style; default false
    # tagsInArticlePreview = true  # enable tags list in the article preview card
    # gridView = false  # show post list as a grid. goes well with paperCards
    # bigArticleTitle = false  # makes the title in the single article view bigger
    # navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
    # enableShadow = false  # shows a shadow around some elements
    # menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
    # inputStyle = "standard" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"
    #
    # enableSearch = true  # enable search page
    # searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
    # searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
    # mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small
    #
    # enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)
    #
    # underlineTitleLinks = true  # show an underline also for links that are titles
    #
    # # enable comments support with commento using the script from your server
    # # commento = "https://example.com/js/commento.js"
    #
    # # enable comments support with cactus comments (cactus.chat)
    # # cactusCommentsSiteName = "example.com"
    # # cactusCommentsServerName = "cactus.chat"
    # # cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"
    #
    # # enable analytics using Plausible
    # #plausibleScriptUrl = "https://something.com/..."
    # #plausibleDomain = "example.com"
    #
    # # enable analytics using Umami
    # # umamiScriptUrl = "https://something.com/..."
    # # umamiWebsiteId = "example-tracking-code"
    #
    # enableShareOnFediverse = false  # enable a button at the end of an article to share it on the fediverse
    # tocBeforeImage = false  # show the table of contents before the main article image; default false
    #
    # # alternative sidebar layout
    # enableSidebarLayout = true
    # tocInSidebar = false  # if the sidebar is enbabled, show the TOC in the sidebar
    #
    # # redirect to baseURL if current URL host doesn't match
    # # useful if deploying in gitlab pages with custom domain and don't want
    # # the username.gitlab.io/website url to persist
    # # this requires you to set baseURL (see above)
    # forceRedirect = false
    #
    # infiniteScrolling = true  # activates infinite scrolling instead of regular pagination
    #                            # NOTE: you need to enable JSON output for this to work!
    #                            #       look at the [outputs] section below
    #
    # enableFooterColumns = false  # activates footer columns, as described below
    # enableJumbotron = false  # enables jumbotron, as described below
    # # related articles will be selected randomly based on tags and shown at
    # # the bottom of the article, after the comments
    # enableRelatedArticles = false
    # relatedArticlesNum = 2  # how many related articles to show
    # randomRelated = false  # sorts related articles in random order (randomized at built time)
[languages]
  [languages.en]
    languageName = "English"
    title = "Wilkuu's site"

    [languages.en.params]
      subtitle = "Wilkuu's home site"
      owner = "Wilkuu"
      keywords = ""
      copyright = "Wilkuu"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Wilkuu.xyz"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects"
        [[languages.en.menu.main]]
          identifier = "tarpit"
          name = "AI Scraper Zone"
          url = "/ai_training_data"

# [menu]
#     # these links will be added to the main navigation menu, sorted by weight
#     # other elements in this menu are added automatically from the "pages" folder
#     # the folder it will look into can be customized with the pages variable
#     # in params above
#     [[menu.main]]
#         identifier = "about"
#         name = "About"
#         url = "/about/"
#         weight = 10
#     # these links (menu.icons) will be added as icon links below the main nav
#     [[menu.icons]]
#         identifier = "github"
#         name = "GitHub"
#         url = "https://github.com/Wilkuu-2"
#         weight = 10
#     [[menu.icons]]
#         identifier = "trashcan"
#         name = "üóëÔ∏è"
#         url = "https://wilkuu.xyz/ai_training_data"
#         weight = 0

# this section is necessary if you want infinite scrolling
# it allows to output the article list as paged JSON so that "pages" can be retrieved via javascript
[outputs]
    home = ["HTML", "JSON", "RSS"]


